all: lab_6a lab_6b own_code

lab_6a: lab_6a.c lab_6a_asm.s
		gcc -o lab_6a lab_6a.c lab_6a_asm.s

lab_6b: lab_6b.c lab_6b_asm.s
		gcc -o lab_6b lab_6b.c lab_6b_asm.s

#lab_6c: lab_6c.s
#		gcc -o lab_6c lab_6c.s

own_code: own_code.c own_code.s
		gcc -o own_code own_code.c own_code.s
